language: cpp
os:
- linux
sudo: required
dist: trusty
compiler:
- clang
- gcc
install:
- if [ "$CXX" = "g++" ]; then g++ -v; else clang -v; fi
- gem install bundler
addons:
  packages:
#  - ninja-build
  - clang
  - libmysqlclient18
  - libboost-thread-dev
  - libboost-system-dev
  - libboost-regex-dev
  - libboost-date-time-dev
  - libboost-program-options-dev
before_script:
- sudo add-apt-repository -y ppa:beineri/opt-qt571-trusty
- sudo apt-get -qq update
- sudo apt-get install -y qt57base qt57tools ninja-build
- QTDIR="/opt/qt57" && PATH="$QTDIR/bin:$PATH"
- source /opt/qt57/bin/qt57-env.sh
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: "./travis.sh"
env:
  global:
  - secure: vMwqCTy+npZOtscC9bUDx1YC2gRPCvP+cHEWrAw9nS1LO2ibw5SvGrokxzIVGojWL3b0StGC5As2ff59uNULcVL3XwUgzu8MWmStcQVewY3BuGrRvhvl8Bl5vEVCLDPB07c28XLo2DLdYD0FSGV+MOWul9pU7zGcKDa3VW79Qxrt8Hlyw29EjBOyKXFGXdQQaBvarSCk5OA2wsd3h/wUZ4euJtcjJUbPoDB+fL1sPKZjDHPBz3vwT4SNZhrmvHOVotN7mt0kpCjJ8IAZy/blAZtEJAXcxYOfkFkUcQqDS0qencA4AVePqFiiosmf5o/veda0C+iTunmW4u+lG10MBQJuzFZ4dSPVZtHbHJg6XciF3+v1iDkGU+t2ADrtaHBQRiBJMPAABaGq4Tv5z1dRoRAU6tZ5BfeeQ/DXQjN+h6sKv28SejojTFBAn2Q5CEqAPGW6fMdp8p6vI3qMNzGO+X2fi4LPmxLwJX75b23n+mZ1rv9VEOP9bN7j+wfJGdGF097gOIzzTmVT+vpGL+kDZ90jDNC6U0CXkS2dlBg0r4GyNY54CU8GOGH0zMxwbGyOE4HErLkSicFXd7w30O5OmnUQ0fnKiez40ps2kny9Mq/mcoG4KM59c8ZDkEEx3kYB21OuCUx5Aafo9wpDFgCOYC/bEGbVhw5f0nv+qxBPqKw=
  - secure: G8LnHgDmOGJo01k6QnETJ35oq1k5cemikjgFreoSvfMGCsaBYAOHU2+CxXZaIogHhbHOwK1ptdevH5g5F6wW/1DtSFJTXSjMw8O5rJa1G+eUkEVf289KJ33HcjyWcu+9KipmleJmw68VA0EZndokglxAoSZccgvCNNV1o/pIyfFPFdws6GlFrx2+ZFnG4GComdTzRfd94cz0ipSktfNlfn+Fuae6D1UkeesO19GE1k6HzPuvNniLH5DlYifhHoguLM3cUtQovgjvgXq9haufZL4AXF46nBn+s0QKxGAFnb40VPs2lryPqdWeMTFYQL/Hu4W915PiFYdf69r9Obk/tXLmh62flDBIM1uHlnF207837cOPrjKI7MLc5/JUKTugiZfcZKf/eccqbgSoa4CT974he2KfwINOdBRBt43nNLfOSqxry8OtY3qNVNFWQ8T8Op/6VLNYjHBjTTgvxz13a7wqIX2El/bC7nwmd3sKaLhkVS3oicdOxd3mY3wJSeoSZLinWDkXUUo1O66lJmGS0D/nWZzIZpnU2OtU+iQPwCEsirEwv4QRZ9db0weMCZfJb87zIROF8Z8ogPUbCGxh9MnLtY58ZCFAyWS0zxcLCPNSAhhOhDvGXSDBmoYqWfEFAEhlJ+2dlsoRRsBnT4zXhjx85tb6+F+RNJ6Kh71zkpQ=
