language: cpp
os:
  - linux
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then g++ -v; else clang -v; fi
  - gem install bundler #cucumber -v 2.0.0

addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - clang
      - libmysqlclient18
#      - qtbase5-dev
#      - qttools5-dev
#      - qttools5-dev-tools
#      - libqt5sql5-mysql 
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-program-options-dev

before_script:
  - sudo add-apt-repository -y ppa:beineri/opt-qt561-trusty 
  - sudo apt-get -qq update
  - sudo apt-get install -y qt56base qt56tools ninja-build 
  - QTDIR="/opt/qt56" && PATH="$QTDIR/bin:$PATH"
  - source /opt/qt56/bin/qt56-env.sh 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: ./travis.sh 
#after_script: cat /home/travis/build/konserw/koferta/build/cucumber/src/cucumber-cpp-stamp/cucumber-cpp-build-*.log

