@echo on
cmake -E make_directory build
IF %APPVEYOR_REPO_TAG% EQU true (
echo %APPVEYOR_REPO_TAG_NAME%
cmake -E chdir build cmake -DKOFERTA_VERSION=%APPVEYOR_REPO_TAG_NAME% -DKOFERTA_SQL_USER=%KOFERTA_SQL_USER% -DKOFERTA_SQL_PWD=%KOFERTA_SQL_PWD% ..
) ELSE (
echo %APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%
cmake -E chdir build cmake -DKOFERTA_VERSION=%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER% -DKOFERTA_SQL_USER=%KOFERTA_SQL_USER% -DKOFERTA_SQL_PWD=%KOFERTA_SQL_PWD% ..
)
cmake --build build --config Release
