@echo on
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
set PATH=%PATH%;%QTDIR%\bin
cmake -E make_directory build
IF %APPVEYOR_REPO_TAG% EQU true (
echo %APPVEYOR_REPO_TAG_NAME%
cmake -E chdir build cmake -DKOFERTA_VERSION=%APPVEYOR_REPO_TAG_NAME% -DKOFERTA_SQL_USER=%KOFERTA_SQL_USER% -DKOFERTA_SQL_PWD=%KOFERTA_SQL_PWD% -DCMAKE_GENERATOR_PLATFORM=x64 ..
) ELSE (
echo %APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%
cmake -E chdir build cmake -DKOFERTA_VERSION=%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER% -DKOFERTA_SQL_USER=%KOFERTA_SQL_USER% -DKOFERTA_SQL_PWD=%KOFERTA_SQL_PWD% -DCMAKE_GENERATOR_PLATFORM=x64 ..
)
cmake --build build --config Release
